/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as DesignPreviewRouteImport } from './routes/design-preview'
import { Route as MapRouteImport } from './routes/map'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as StitchPreviewRouteImport } from './routes/stitch-preview'
import { Route as SurgeryRouteImport } from './routes/surgery'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCredentialsRouteImport } from './routes/admin.credentials'
import { Route as AdminLiveRouteImport } from './routes/admin.live'
import { Route as AdminLocumRouteImport } from './routes/admin.locum'
import { Route as AdminPhysicianRouteImport } from './routes/admin.physician'
import { Route as AdminPhysioRouteImport } from './routes/admin.physio'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminWellnessRouteImport } from './routes/admin.wellness'
import { Route as DevRaceAcceptRouteImport } from './routes/dev.race-accept'
import { Route as PhysioBookRouteImport } from './routes/physio.book'
import { Route as PhysioVisitsRouteImport } from './routes/physio.visits'
import { Route as ProviderAvailabilityRouteImport } from './routes/provider.availability'
import { Route as ProviderEarningsRouteImport } from './routes/provider.earnings'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as SharedAiTokenRouteImport } from './routes/shared.ai.$token'
import { Route as ApiPublicPushDispatchRouteImport } from './routes/api/public/push/dispatch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignPreviewRoute = DesignPreviewRouteImport.update({
  id: '/design-preview',
  path: '/design-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const StitchPreviewRoute = StitchPreviewRouteImport.update({
  id: '/stitch-preview',
  path: '/stitch-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const SurgeryRoute = SurgeryRouteImport.update({
  id: '/surgery',
  path: '/surgery',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCredentialsRoute = AdminCredentialsRouteImport.update({
  id: '/admin/credentials',
  path: '/admin/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLiveRoute = AdminLiveRouteImport.update({
  id: '/admin/live',
  path: '/admin/live',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLocumRoute = AdminLocumRouteImport.update({
  id: '/admin/locum',
  path: '/admin/locum',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPhysicianRoute = AdminPhysicianRouteImport.update({
  id: '/admin/physician',
  path: '/admin/physician',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPhysioRoute = AdminPhysioRouteImport.update({
  id: '/admin/physio',
  path: '/admin/physio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWellnessRoute = AdminWellnessRouteImport.update({
  id: '/admin/wellness',
  path: '/admin/wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRaceAcceptRoute = DevRaceAcceptRouteImport.update({
  id: '/dev/race-accept',
  path: '/dev/race-accept',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysioBookRoute = PhysioBookRouteImport.update({
  id: '/physio/book',
  path: '/physio/book',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysioVisitsRoute = PhysioVisitsRouteImport.update({
  id: '/physio/visits',
  path: '/physio/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderAvailabilityRoute = ProviderAvailabilityRouteImport.update({
  id: '/provider/availability',
  path: '/provider/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderEarningsRoute = ProviderEarningsRouteImport.update({
  id: '/provider/earnings',
  path: '/provider/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const SharedAiTokenRoute = SharedAiTokenRouteImport.update({
  id: '/shared/ai/$token',
  path: '/shared/ai/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushDispatchRoute = ApiPublicPushDispatchRouteImport.update({
  id: '/api/public/push/dispatch',
  path: '/api/public/push/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/design-preview': typeof DesignPreviewRoute
  '/map': typeof MapRoute
  '/mcp': typeof McpRoute
  '/stitch-preview': typeof StitchPreviewRoute
  '/surgery': typeof SurgeryRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/locum': typeof AdminLocumRoute
  '/admin/physician': typeof AdminPhysicianRoute
  '/admin/physio': typeof AdminPhysioRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wellness': typeof AdminWellnessRoute
  '/dev/race-accept': typeof DevRaceAcceptRoute
  '/physio/book': typeof PhysioBookRoute
  '/physio/visits': typeof PhysioVisitsRoute
  '/provider/availability': typeof ProviderAvailabilityRoute
  '/provider/earnings': typeof ProviderEarningsRoute
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/shared/ai/$token': typeof SharedAiTokenRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/design-preview': typeof DesignPreviewRoute
  '/map': typeof MapRoute
  '/mcp': typeof McpRoute
  '/stitch-preview': typeof StitchPreviewRoute
  '/surgery': typeof SurgeryRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/locum': typeof AdminLocumRoute
  '/admin/physician': typeof AdminPhysicianRoute
  '/admin/physio': typeof AdminPhysioRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wellness': typeof AdminWellnessRoute
  '/dev/race-accept': typeof DevRaceAcceptRoute
  '/physio/book': typeof PhysioBookRoute
  '/physio/visits': typeof PhysioVisitsRoute
  '/provider/availability': typeof ProviderAvailabilityRoute
  '/provider/earnings': typeof ProviderEarningsRoute
  '/admin': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/shared/ai/$token': typeof SharedAiTokenRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/design-preview': typeof DesignPreviewRoute
  '/map': typeof MapRoute
  '/mcp': typeof McpRoute
  '/stitch-preview': typeof StitchPreviewRoute
  '/surgery': typeof SurgeryRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/locum': typeof AdminLocumRoute
  '/admin/physician': typeof AdminPhysicianRoute
  '/admin/physio': typeof AdminPhysioRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wellness': typeof AdminWellnessRoute
  '/dev/race-accept': typeof DevRaceAcceptRoute
  '/physio/book': typeof PhysioBookRoute
  '/physio/visits': typeof PhysioVisitsRoute
  '/provider/availability': typeof ProviderAvailabilityRoute
  '/provider/earnings': typeof ProviderEarningsRoute
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/shared/ai/$token': typeof SharedAiTokenRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bookings'
    | '/design-preview'
    | '/map'
    | '/mcp'
    | '/stitch-preview'
    | '/surgery'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/credentials'
    | '/admin/live'
    | '/admin/locum'
    | '/admin/physician'
    | '/admin/physio'
    | '/admin/users'
    | '/admin/wellness'
    | '/dev/race-accept'
    | '/physio/book'
    | '/physio/visits'
    | '/provider/availability'
    | '/provider/earnings'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/shared/ai/$token'
    | '/api/public/push/dispatch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bookings'
    | '/design-preview'
    | '/map'
    | '/mcp'
    | '/stitch-preview'
    | '/surgery'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/credentials'
    | '/admin/live'
    | '/admin/locum'
    | '/admin/physician'
    | '/admin/physio'
    | '/admin/users'
    | '/admin/wellness'
    | '/dev/race-accept'
    | '/physio/book'
    | '/physio/visits'
    | '/provider/availability'
    | '/provider/earnings'
    | '/admin'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/shared/ai/$token'
    | '/api/public/push/dispatch'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bookings'
    | '/design-preview'
    | '/map'
    | '/mcp'
    | '/stitch-preview'
    | '/surgery'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/credentials'
    | '/admin/live'
    | '/admin/locum'
    | '/admin/physician'
    | '/admin/physio'
    | '/admin/users'
    | '/admin/wellness'
    | '/dev/race-accept'
    | '/physio/book'
    | '/physio/visits'
    | '/provider/availability'
    | '/provider/earnings'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/shared/ai/$token'
    | '/api/public/push/dispatch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BookingsRoute: typeof BookingsRoute
  DesignPreviewRoute: typeof DesignPreviewRoute
  MapRoute: typeof MapRoute
  McpRoute: typeof McpRoute
  StitchPreviewRoute: typeof StitchPreviewRoute
  SurgeryRoute: typeof SurgeryRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminCredentialsRoute: typeof AdminCredentialsRoute
  AdminLiveRoute: typeof AdminLiveRoute
  AdminLocumRoute: typeof AdminLocumRoute
  AdminPhysicianRoute: typeof AdminPhysicianRoute
  AdminPhysioRoute: typeof AdminPhysioRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWellnessRoute: typeof AdminWellnessRoute
  DevRaceAcceptRoute: typeof DevRaceAcceptRoute
  PhysioBookRoute: typeof PhysioBookRoute
  PhysioVisitsRoute: typeof PhysioVisitsRoute
  ProviderAvailabilityRoute: typeof ProviderAvailabilityRoute
  ProviderEarningsRoute: typeof ProviderEarningsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  SharedAiTokenRoute: typeof SharedAiTokenRoute
  ApiPublicPushDispatchRoute: typeof ApiPublicPushDispatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-preview': {
      id: '/design-preview'
      path: '/design-preview'
      fullPath: '/design-preview'
      preLoaderRoute: typeof DesignPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stitch-preview': {
      id: '/stitch-preview'
      path: '/stitch-preview'
      fullPath: '/stitch-preview'
      preLoaderRoute: typeof StitchPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surgery': {
      id: '/surgery'
      path: '/surgery'
      fullPath: '/surgery'
      preLoaderRoute: typeof SurgeryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/credentials': {
      id: '/admin/credentials'
      path: '/admin/credentials'
      fullPath: '/admin/credentials'
      preLoaderRoute: typeof AdminCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/live': {
      id: '/admin/live'
      path: '/admin/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AdminLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/locum': {
      id: '/admin/locum'
      path: '/admin/locum'
      fullPath: '/admin/locum'
      preLoaderRoute: typeof AdminLocumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/physician': {
      id: '/admin/physician'
      path: '/admin/physician'
      fullPath: '/admin/physician'
      preLoaderRoute: typeof AdminPhysicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/physio': {
      id: '/admin/physio'
      path: '/admin/physio'
      fullPath: '/admin/physio'
      preLoaderRoute: typeof AdminPhysioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wellness': {
      id: '/admin/wellness'
      path: '/admin/wellness'
      fullPath: '/admin/wellness'
      preLoaderRoute: typeof AdminWellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/race-accept': {
      id: '/dev/race-accept'
      path: '/dev/race-accept'
      fullPath: '/dev/race-accept'
      preLoaderRoute: typeof DevRaceAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physio/book': {
      id: '/physio/book'
      path: '/physio/book'
      fullPath: '/physio/book'
      preLoaderRoute: typeof PhysioBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physio/visits': {
      id: '/physio/visits'
      path: '/physio/visits'
      fullPath: '/physio/visits'
      preLoaderRoute: typeof PhysioVisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/availability': {
      id: '/provider/availability'
      path: '/provider/availability'
      fullPath: '/provider/availability'
      preLoaderRoute: typeof ProviderAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/earnings': {
      id: '/provider/earnings'
      path: '/provider/earnings'
      fullPath: '/provider/earnings'
      preLoaderRoute: typeof ProviderEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/ai/$token': {
      id: '/shared/ai/$token'
      path: '/shared/ai/$token'
      fullPath: '/shared/ai/$token'
      preLoaderRoute: typeof SharedAiTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/dispatch': {
      id: '/api/public/push/dispatch'
      path: '/api/public/push/dispatch'
      fullPath: '/api/public/push/dispatch'
      preLoaderRoute: typeof ApiPublicPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BookingsRoute: BookingsRoute,
  DesignPreviewRoute: DesignPreviewRoute,
  MapRoute: MapRoute,
  McpRoute: McpRoute,
  StitchPreviewRoute: StitchPreviewRoute,
  SurgeryRoute: SurgeryRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminCredentialsRoute: AdminCredentialsRoute,
  AdminLiveRoute: AdminLiveRoute,
  AdminLocumRoute: AdminLocumRoute,
  AdminPhysicianRoute: AdminPhysicianRoute,
  AdminPhysioRoute: AdminPhysioRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWellnessRoute: AdminWellnessRoute,
  DevRaceAcceptRoute: DevRaceAcceptRoute,
  PhysioBookRoute: PhysioBookRoute,
  PhysioVisitsRoute: PhysioVisitsRoute,
  ProviderAvailabilityRoute: ProviderAvailabilityRoute,
  ProviderEarningsRoute: ProviderEarningsRoute,
  AdminIndexRoute: AdminIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  SharedAiTokenRoute: SharedAiTokenRoute,
  ApiPublicPushDispatchRoute: ApiPublicPushDispatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
